In [1]:
class demo:
    def fact(self,n):
        fact=1
        while(n!=0):
            fact=fact*n
            n=n-1
        return fact
p= demo()
print(p.fact(5))

120


In [2]:
class demo1:
    def __init__(self,p1,p2):
        self.p1=p1
        self.p2=p2
    def add(self,p1,p2):
        return p1+p2
c1=demo1(10,20)
print(c1.add(100,200))

300


In [3]:
# some inheritance
# parent class
class person(object):
    #constructor
    def __init__(self,name):
        self.name = name
    def getname(self):
        return self.name
    def isemployee(self):
        return False
# Derived Class
class employee(person):
    def isemployee(self):
        return True
emp=person("Anil")
print(emp.getname(),emp.isemployee())
emp1=employee("Kedhar")
print(emp1.getname(),emp1.isemployee())

Anil False
Kedhar True


# Python numpy

In [4]:
import numpy as np
list=[1,2,3,4]
array=np.array(list)
print(array)

[1 2 3 4]


In [5]:
list=[1,2,3,4]
array=np.array(list)
print(array.shape)
print(array.dtype)

(4,)
int32


In [7]:
# Re-shape the Given array
# numpy.reshape(arrayName,reshape,order='c')
a1=np.array([(1,2,3),(4,5,6)])
print(a1)
a1.reshape(3,2)

[[1 2 3]
 [4 5 6]]


array([[1, 2],
       [3, 4],
       [5, 6]])

In [8]:
a1 = np.array([(1,2,3,),(4,5,6)])
print("First Row : ",a1[0])

First Row :  [1 2 3]


In [9]:
c1=np.array([(1,2),(3,4)])
c2=np.array([(3,4),(1,2)])
np.dot(c1,c2)

array([[ 5,  8],
       [13, 20]])

In [10]:
c1=np.array([(1,2)])
c2=np.array([(3,4)])
np.dot(c1,c2)

ValueError: shapes (1,2) and (1,2) not aligned: 2 (dim 1) != 1 (dim 0)

# pandas Basics